Upm support
InfectedBytes/gj-unity-api pull request #51
Opened 2022-02-06 12:21 UTC by bilal-arikan

Hi,
I moved the plugins folders,
created package.json,
removed default settings asset

I haven't tried it in a real project yet.

2022-02-17 15:54 UTC, InfectedBytes requested changes
Sorry for the late response, but I finally got some time to check your PR out.

2022-02-17 15:54 UTC, InfectedBytes commented on Assets/GameJolt/Demo.meta
> +guid: 001272e13cb1abe428a1e460e727d0fc
```suggestion
guid: b91b6ee24b8365c46bc58bc634563d1b
```
don't change any guids of existing files

2022-02-17 15:54 UTC, InfectedBytes commented on Assets/GameJolt/Runtime.meta
> +guid: ab05197c209c5c7488f63c852f3d61f7
```suggestion
guid: 9b696b31cf14e0542ba0f0d864c955dd
```
don't modify the guids of existing files

2022-02-17 15:54 UTC, InfectedBytes commented on README.md
> +"com.gamejolt.api": "https://github.com/bilal-arikan/gamejolt-unity-api.git?path=/Assets/GameJolt#2.5.7",
please use the main repository https://github.com/InfectedBytes/gj-unity-api.git?path=/Assets/GameJolt#2.5.7

2022-02-17 20:25 UTC, bilal-arikan commented
Thanks for your response,

Changing value of `Editor\GameJolt\Tools.cs 'ManagerPrefabPath'`  probably broke the old .unitypackage file structure. It may be necessary to find a solution to this before merge.

2022-02-18 15:39 UTC, InfectedBytes commented
> Thanks for your response,
> 
> Changing value of `Editor\GameJolt\Tools.cs 'ManagerPrefabPath'` probably broke the old .unitypackage file structure. It may be necessary to find a solution to this before merge.

right, good point. Probably best to keep both paths, if the old path exists -> move file (+meta file) to new path

2022-02-19 08:48 UTC, InfectedBytes commented
I've created a upm-support branch in my repo too, so if you just retarget this PR to that branch, we can merge it and I'll take care of some open issues, like upgrading from older packages and stuff.

2022-02-19 09:42 UTC, closed without merging